
-- Delete existing wrong quiz questions for Material Creation Using AI
DELETE FROM lesson_quizzes WHERE lesson_id = '51c470fd-f9c6-46cd-9165-55783d450f71';

-- Insert correct quiz questions about Material Creation Using AI
INSERT INTO lesson_quizzes (lesson_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation) VALUES
('51c470fd-f9c6-46cd-9165-55783d450f71', 'What is the primary advantage of using AI for material creation in MDG?', 'Faster database backups', 'Automated data population and classification of material attributes', 'Reduced server storage costs', 'Simplified user authentication', 'B', 'AI assists in automatically populating and classifying material attributes, reducing manual effort and improving data quality during material creation.'),
('51c470fd-f9c6-46cd-9165-55783d450f71', 'Which AI capability helps suggest accurate material descriptions during creation?', 'Image recognition', 'Natural Language Processing (NLP)', 'Network optimization', 'File compression', 'B', 'NLP enables the system to analyze and suggest accurate, standardized material descriptions based on existing data patterns.'),
('51c470fd-f9c6-46cd-9165-55783d450f71', 'How does AI reduce duplicate materials during the creation process?', 'By deleting old materials automatically', 'By matching new entries against existing records using similarity algorithms', 'By limiting the number of materials a user can create', 'By requiring manual approval for every material', 'B', 'AI uses similarity and matching algorithms to identify potential duplicates before a new material is created, preventing redundant records.'),
('51c470fd-f9c6-46cd-9165-55783d450f71', 'What type of data does AI primarily use to auto-classify materials?', 'User login history', 'Historical material master records and taxonomies', 'Server performance metrics', 'Email communication logs', 'B', 'AI leverages historical material master data and established taxonomies to automatically classify new materials into the correct categories.'),
('51c470fd-f9c6-46cd-9165-55783d450f71', 'What is a key benefit of AI-assisted material creation for data governance?', 'It eliminates the need for data stewards', 'It ensures consistency and compliance with organizational naming standards', 'It removes all validation rules', 'It allows unrestricted data entry', 'B', 'AI-assisted creation enforces organizational naming conventions and standards, ensuring consistent and compliant material records.');
