
INSERT INTO public.course_lessons (id, course_id, title, description, video_url, lesson_order, is_free)
VALUES
  ('9621c21d-1144-4c4a-acb4-eadf14bdc53b', 72, 'EAM Objects Data Migration (Maximo to S4)', 'Migrate EAM objects from IBM Maximo into SAP S/4HANA.', 'supabase://course-videos/EAM Objects Data Migration (Maximo to S4).mp4', (SELECT COALESCE(MAX(lesson_order),0)+1 FROM public.course_lessons WHERE course_id=72), false),
  ('aa8c4005-a729-4fcb-ae59-6e10cdd06022', 72, 'Assets & Locations - Data Migration From Maximo to S4Hana', 'Migrate Assets and Functional Locations from Maximo to SAP S/4HANA.', 'supabase://course-videos/Assets & Locations-Data Migration From Maximo to S4Hana.mp4', (SELECT COALESCE(MAX(lesson_order),0)+2 FROM public.course_lessons WHERE course_id=72), false),
  ('4a730748-8da7-4cdc-868b-47eb92f6d660', 72, 'Use of PiLog to Perform Smart Data Migration from Maximo to SAP', 'Leverage PiLog tooling to perform a smart, governed data migration from Maximo to SAP.', 'supabase://course-videos/Use of PiLog to Perform Smart Data Migration from Maximo to SAP.mp4', (SELECT COALESCE(MAX(lesson_order),0)+3 FROM public.course_lessons WHERE course_id=72), false),
  ('b116de62-5f9d-40c0-b35a-db32c45c1a9d', 14, 'DQG Suite Integration with HANA, BNAC', 'Data Quality & Governance Suite integration patterns with SAP HANA and BNAC.', 'supabase://course-videos/DQG Suite Integration with HANA, BNAC.mp4', (SELECT COALESCE(MAX(lesson_order),0)+1 FROM public.course_lessons WHERE course_id=14), false),
  ('f27f94e2-d92c-4b0e-9b73-1ec8675213e7', 14, 'Use Case-1 & 2 APM Integration with SAP S4 HANA, IoT Sensor & MES, Process Data', 'Two end-to-end use cases for APM integration with SAP S/4HANA, IoT sensors, MES and process data.', 'supabase://course-videos/Use Case-1 & 2 APM Integration with SAP S4 HANA,IoT Sensor & MES, Process Data.mp4', (SELECT COALESCE(MAX(lesson_order),0)+2 FROM public.course_lessons WHERE course_id=14), false),
  ('300f736e-7d99-472b-bec4-5303b6915f5e', 13, 'SAP Material Master End to End Migration Process', 'End-to-end migration process for SAP Material Master data.', 'supabase://course-videos/SAP Material Master End to End Migration Process.mp4', (SELECT COALESCE(MAX(lesson_order),0)+1 FROM public.course_lessons WHERE course_id=13), false);
